- name: Añadir repositorios MySQL
  hosts: instalar
  tasks:
  
  - name: Añadir la repo de MySQL
    yum:
      name: http://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
      state: present

  - name: Instalar MySQL
    yum:
      name: mysql-server
      state: present

  - name: Iniciar el servicio MySQLd
    service:
      name: mysqld
      state: started
