# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

		config.vm.provision "shell", inline: <<-SHELL
		apt-get update -y
		apt-get install -y apache2
		
	SHELL


	config.vm.define :ubuntu do |ubuntu|
	
		ubuntu.vm.box = "hashicorp/precise64"
		ubuntu.vm.host_name = "ubuntu"
		ubuntu.vm.network "private_network", ip: "192.168.1.50"
		
	end
	
	config.vm.define :centos do |centos|
		centos.vm.box = "centos/7"
		centos.vm.host_name = "centos"
		centos.vm.network "private_network", ip: "192.168.1.51"
		
	end
	
end
