# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

		config.vm.provision "shell", inline: <<-SHELL
		apt-get update -y
		apt-get install -y apache2
		
	SHELL


	config.vm.define :ubuntu do |ubuntu|
	
		ubuntu.vm.box = "ubuntu/xenial64"
		ubuntu.vm.host_name = "ubuntu"
		ubuntu.vm.network "private_network", ip: "192.168.50.3"

	end
	
	config.vm.define :centos do |centos|
		centos.vm.box = "centos/7"
		centos.vm.host_name = "centos"
		centos.vm.network "private_network", ip: "192.168.50.4"

	end

	config.vm.define :mongoVM do |mongoVM|
		mongoVM.vm.hostname = "mongoVM"
		mongoVM.vm.box = "ubuntu/xenial64"
		mongoVM.vm.network "private_network", ip: "192.168.50.5"
		mongoVM.vm.network "forwarded_port", guest: 27017, host: 27017
		mongoVM.vm.provision "shell", inline: <<-MONGO
			sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
			echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
			sudo apt-get update -y
			sudo apt-get install -y mongodb-org
			sudo service mongod start
		MONGO
	end

end
